### ISSUE TITLE
Why have not import protobuf include file at simulation case file?

### ISSUE THREAD

**Issue by thinkerou** [macchiatow/gatling-grpc#8]
[here](https://github.com/macchiatow/gatling-grpc/blob/master/src/test/scala/me/macchiatow/gatling/grpc/BlockingGrpcSimulation.scala#L22) use `FundsRequest` but not import `me.macchiatow.gatling.grpc.FundsRequest`. Thanks a lot!

**Comment by macchiatow** [comment]
dont get the point

**Comment by thinkerou** [comment]
OK, thanks!
